n=int(input())
while(n!=0):
    if(n>=1000):
        print("M",end="")
        n=n-1000
    elif  n>=900:
        print("CM",end="")
        n=n-900
    elif n>=500:
        print("D",end="")
        n=n-500
    elif n>=400:
        print("CD",end="")
        n=n-400
    elif n>=100:
        print("C",end="")
        n=n-100
    elif n>=90:
        print("XC",end="")
        n=n-90
    elif n>=50:
        print("L",end="")
        n=n-50
    elif n>=40:
        print("XL",end="")
        n=n-40
    elif n>=10:
        print("X",end="")
        n=n-10
    elif n>=5:
        print("V",end="")
        n=n-5
    elif n>=1:
        print("I",end="")
        n=n-1